name: Fetch Data

on: 
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./olympics
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
    
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Install the python version needed
    
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas numpy matplotlib seaborn lxml
      - name: Execute Python script # Run the run.py to get the latest data
        run: python data.py
      - name: Commit and Push
        run: |
          git config --global user.name 'StefanWG'
          git config --global user.email 'stefan.walzergoldfeld@gmail.com'
          git commit -am "Automated data fetch"
          git push 
