name: Fetch Data

on: 
  schedule:
    - cron: "10 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
    
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Install the python version needed
          cache: 'pip'
    
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas numpy matplotlib seaborn 
      - name: Go To Directory
        run: cd olympics
      - name: Execute Python script # Run the run.py to get the latest data
        run: python data.py
